Revert "flake: update all deps"
The build of nodejs is failing:

error: builder for '/nix/store/m7gxzgk460q28z52xh211r0gwvz4ak24-nodejs-20.19.0.drv' failed with exit code 2;
       last 25 log lines:
       > ok 3997 known_issues/test-vm-function-declaration-uses-define
       >   ---
       >   duration_ms: 65.07400
       >   ...
       > ok 3998 known_issues/test-vm-ownkeys
       >   ---
       >   duration_ms: 59.36700
       >   ...
       > ok 3999 known_issues/test-vm-ownpropertynames
       >   ---
       >   duration_ms: 51.77700
       >   ...
       > ok 4000 known_issues/test-vm-ownpropertysymbols
       >   ---
       >   duration_ms: 58.80000
       >   ...
       > ok 4001 known_issues/test-vm-timeout-escape-nexttick
       >   ---
       >   duration_ms: 887.85800
       >   ...
       >
       > Failed tests:
       > out/Release/node /private/tmp/nix-build-nodejs-20.19.0.drv-0/node-v20.19.0/test/parallel/test-fs-stat-bigint.js
       > out/Release/node /private/tmp/nix-build-nodejs-20.19.0.drv-0/node-v20.19.0/test/parallel/test-module-loading-error.js
       > make: *** [Makefile:557: test-ci-js] Error 1

This reverts commit 68a0f25965fd61b4f9062be55114a3eb575e8819.